config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :contacts, :only => [:new, :create]

  resources :users do
    resources :books, :only => [:index]
  end

  resources :books do
    resources :comments, :only => [:create, :destroy]
  end

  #resources :comments, :only => [:index]
  root 'top#index'
  get 'about/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'comments/index'

  # twitterログイン
  get '/auth/:provider/callback' => 'sessions#create'

  # ログアウト
  get '/signout' => 'sessions#destroy'

  # テストユーザー
  get '/testlogin' => 'sessions#testuser'

  # お気に入りボタン
  post '/likes/:id' => 'likes#likes?'
  post '/likes/:id/like' => 'likes#like'

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  ALLOWED_CONTENT_TYPES = %q{
    image/jpeg
    image/png
    image/gif
    image/bmp
  }
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :picture
  attribute :new_picture
  attribute :remove_picture, :boolean

  # book が削除されると、同時にコメントも消される
  has_many :comments, dependent: :destroy

  belongs_to :user, class_name: 'User', foreign_key: 'user_id'

  # バリデーション
  validates :title, presence: true
  validates :author, presence: true
  # new_pictureが nil でも false でも無い場合に限りバリデーションを行う
  validate  if: :new_picture do
    # respond_to はあるオブジェクトが特定のメソッドを持っているかどうかを調べる
    if new_picture.respond_to?(:content_type)
      unless new_picture.content_type.in?(ALLOWED_CONTENT_TYPES)
        errors.add(:new_picture, :invalid_image_type)
      end
    else
      errors.add(:new_picture, :invalid)
    end
  end

  before_save do
    if new_picture
      self.picture = new_picture
    elsif remove_picture
      self.picture.purge
    end
  end

  scope :get_by_title, ->(title) {where("title like ?", "%#{title}%")}

  def self.search(search)
    if search
      Book.where(['content LIKE ?', "%#{search}%"])
    else
      Book.all
    end
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :title, class_name: "Book", foreign_key: "book_id"

  validates :body, presence: true

  acts_as_likeable

  # 今日投稿された Comment を取得
  scope :created_today, -> { where(posted_at: Time.zone.now.beginning_of_day) }

  # 昨日投稿された Comment を取得
  scope :created_yesterday, -> { where(posted_at: 1.day.ago.all_day) }

  # 3日前に投稿された Comment を取得
  scope :created_three_days_ago, -> { where(posted_at: 3.days.ago.all_day) }

  # 一週間前に投稿された Comment を取得
  scope :created_a_week_ago, -> { where(posted_at: 1.week.ago.all_day) }

  # 一ヶ月前に投稿された Comment を取得
  scope :created_a_month_ago, -> { where(posted_at: 1.month.ago.all_day) }

end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true, length: {maximum:255},
                    format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
  validates :message, presence: true
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/special_book.rb
class SpecialBook < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :books, dependent: :destroy

  acts_as_liker

  def self.find_or_create_from_auth_hash(auth_hash)
    provider = auth_hash[:provider] #providerはどのサービスで認証したのかを見分けるもの
    uid = auth_hash[:uid]
    # name = auth_hash[:name]
    # image = auth_hash[:info][:image]

    # ()の中の条件のものが見つければ取得し、なければ新しく作成するというメソッド
    self.find_or_create_by(provider: provider,uid: uid) do |user|
      user.name = name
      # user.image = image
    end
  end

end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def index
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  protect_from_forgery :except => ["destroy"]
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :current_user, only: [:new, :create]
  # テストユーザーでログインしている時の制限
  before_action :if_not_admin, only: [:new, :edit, :create, :update, :destroy]

  def index
    @user = User.find(session[:user_id])
    @books = Book.where(user_id: session[:user_id]).order(created_at: :desc).page(params[:page]).per(6)
    if params[:title].present?
      @books = @books.get_by_title(params[:title])
    end
  end

  def show
    @user = User.find(session[:user_id])
    @comments = @book.comments
    @comment = Comment.new
  end

  def new
    @book = Book.new
  end

  def edit
  end

  def create
    @user = User.find(session[:user_id])
    @book = Book.new(book_params)
    @book.user_id = @user.id
    if @book.save
      redirect_to @book
    else
      render "new"
    end
  end

  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @books = Book.search(params[:search])
  end

  private

    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:title, :author, :picture, :new_picture, :remove_picture, :user_id)
    end

end

app/controllers/top_controller.rb
class TopController < ApplicationController

  #application.html.erbを適用したくない
  def index
    render layout: false
  end
  
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div id="wrap">
      <%= render "shared/header" %>
      <div id="contents">
        <div class="containner">
          <%= yield %>
        </div>
      </div>
      <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.present? %>
  <div id="errors">
    <h3>エラーがあります</h3>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="py-4 bg-dark text-white">
  <div class="container text-center">
    <ul class="nav justify-content-center mb-3">
      <li class="nev-item">
        <a class="footer_nav-link footer-text" href="/">TOP</a>
      </li>
      <% if logged_in? %>
        <li class="nev-item">
          <%= link_to "BOOKS", user_books_path(session[:user_id]), class: "footer_nav-link" %><span class="sr-only">(current)</span>
        </li>
        <li class="nev-item">
          <%= link_to "SENTENCE", comments_index_path, class: "footer_nav-link" %><span class="sr-only">(current)</span>
        </li>
      <% end %>
      <li class="nev-item">
        <%= link_to "CONTACT", new_contact_path, class: "footer_nav-link" %><span class="sr-only">(current)</span>
      </li>
    </ul>
    <p><small>Copyright &copy;2019 BOOKMEMO, All Rights Reserved.</small></p>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="globalHeader">
  <div class="humburger_menu_bg">
  </div>
  <div class="humburger_menu">
    <span class="bar1"></span>
    <span class="bar2"></span>
    <span class="bar3"></span>
  </div>
   <nav>
     <a href="/">
       <%= image_tag "/images/aikon-white.png", class: "site_logo" %>
     </a>
     <ul class="globalNavi">
       <% if logged_in? %>
         <li class="nav-item">
           <%= link_to(user_books_path(session[:user_id])) do %>
             <i class="fas fa-book"></i>
             <%= link_to "BOOKS", user_books_path(session[:user_id]), class: "nav-link" %><span class="sr-only">(current)</span>
           <% end %>
         </li>
         <li class="nav-item">
           <%= link_to(comments_index_path) do %>
             <i class="fas fa-pencil-alt"></i>
             <%= link_to "SENTENCE", comments_index_path, class: "nav-link" %><span class="sr-only">(current)</span>
           <% end %>
         </li>
       <% end %>
       <li class="nav-item">
         <%= link_to(new_contact_path) do %>
           <i class="far fa-envelope"></i>
           <%= link_to "CONTACT", new_contact_path, class: "nav-link" %><span class="sr-only">(current)</span>
         <% end %>
       </li>
       <li class="nav-item">
         <% if logged_in? %>
           <i class="far fa-times-circle"></i>
           <%= link_to 'LOGOUT', '/signout', class: "nav-link" %><span class="sr-only">(current)</span>
         <% else %>
           <i class="fab fa-twitter"></i>
           <%= link_to "LOGIN", '/auth/twitter', class: "nav-link btn-black" %><span class="sr-only">(current)</span>
         <% end %>
       </li>
       <li class="nav-item">
         <% if current_user.nil? %>
           <%= link_to(testlogin_path) do %>
             <i class="fas fa-user"></i>
             <%= link_to "TESTUSER", testlogin_path, class: "nav-link" %><span class="sr-only">(current)</span>
           <% end %>
         <% end %>
       </li>
     </ul>
   </nav><!-- /.globalNavi -->
</header>